name: "Node Continues integration"

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
  
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-node@v2.4.1
          with:
            node-version: '18'

        - run: npm ci

        - run: npm run build